apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jhub-1-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /(.*)
        backend:
          service:
            name: proxy-public
            port:
              number: 80
